In [59]:
## Data 2 Reviews

In [60]:
import os
os.listdir()

['.git',
 '.ipynb_checkpoints',
 'dictionary.ipynb',
 'README.md',
 'reviews.json',
 'scrape_reviewstokped.ipynb',
 'tokopedia_scrape_all.csv']

In [61]:
import json
from collections import Counter
import re
import nltk
from nltk.corpus import stopwords

nltk.download("stopwords")

# Load file reviews.json
with open("reviews.json", "r", encoding="utf-8") as f:
    data = json.load(f)

texts = [d["message"] for d in data if "message" in d]

stop_words = set(stopwords.words("indonesian"))

all_words = []
for text in texts:
    words = re.findall(r"\w+", text.lower())
    filtered = [w for w in words if w not in stop_words]  # buang stopwords
    all_words.extend(filtered)

# Hitung frekuensi kata
counter = Counter(all_words)

top_100 = counter.most_common(100)

for word, freq in top_100:
    print(word, ":", freq)

barang : 108
sesuai : 105
nya : 101
bagus : 93
harga : 90
suara : 53
bass : 51
kualitas : 46
mantap : 44
cepat : 43
suaranya : 41
yg : 34
ya : 34
pengiriman : 33
lumayan : 31
produk : 31
ok : 27
banget : 25
terima : 24
barangnya : 22
gak : 22
seller : 21
berfungsi : 20
ga : 19
headset : 18
pesanan : 18
kasih : 18
packing : 18
aja : 17
deskripsi : 17
beli : 16
sebelah : 16
oke : 16
jernih : 15
bassnya : 15
respon : 15
thanks : 15
tp : 15
sih : 14
gan : 14
good : 14
murah : 13
kurir : 12
harganya : 12
dah : 12
amp : 11
2 : 11
udah : 11
pengirimannya : 11
puas : 11
dikirim : 11
makasih : 10
sukses : 10
terimakasih : 10
rapi : 10
aman : 10
awet : 10
pas : 10
diterima : 9
warna : 9
semoga : 9
nyampe : 8
nggak : 8
produknya : 8
proses : 8
merah : 8
hitam : 8
kabel : 8
pesan : 8
rapih : 8
segitu : 8
bgt : 8
top : 8
desainnya : 7
modern : 7
cempreng : 7
1 : 7
nyaman : 7
dipakai : 7
terjangkau : 7
gk : 7
toko : 7
kirim : 7
pokoknya : 7
tdk : 7
39 : 7
tokopedia : 7
mendem : 7
dipake : 7
cepet : 7
liger : 7
flash : 7
sale : 7
enak : 7
kiri : 7
34 : 6
memuaskan : 6
yaa : 6
parah : 6
maaf : 6

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\vivin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [62]:
# top_100 is a list of tuples (word, freq)
df_top_words2 = pd.DataFrame(top_100, columns=['word', 'count'])
df_top_words2.head(40)

          word  count
0       barang    108
1       sesuai    105
2          nya    101
3        bagus     93
4        harga     90
5        suara     53
6         bass     51
7     kualitas     46
8       mantap     44
9        cepat     43
10    suaranya     41
11          yg     34
12          ya     34
13  pengiriman     33
14     lumayan     31
15      produk     31
16          ok     27
17      banget     25
18      terima     24
19   barangnya     22
20         gak     22
21      seller     21
22   berfungsi     20
23          ga     19
24     headset     18
25     pesanan     18
26       kasih     18
27     packing     18
28         aja     17
29   deskripsi     17
30        beli     16
31     sebelah     16
32         oke     16
33      jernih     15
34     bassnya     15
35      respon     15
36      thanks     15
37          tp     15
38         sih     14
39         gan     14

In [63]:
## Data 1 Product

In [64]:
import pandas as pd

In [65]:
df = pd.read_csv('tokopedia_scrape_all.csv')
df.head()

,product_id,product_name,url,description,price,sold_count,rating,total_stock,category
0,2618801377,Piano Elektronik Payment Mr. D 2,https://www.tokopedia.com/miracle-piano-maestr...,pengiriman seluruh Indonesia Jakarta Merupak...,20300000,1,NaN,9,Speaker
1,1418259858,mesin cuci lg 15kg f2515stgw(GARANSI RESMI),https://www.tokopedia.com/memory-elektronik-ja...,Tanyakan ketersediaan stock terlebih dahulu\nF...,11100000,1,5.0,5,Mesin Cuci
2,12881922184,Smart TV XIAOMI L32M8-A2ID 32 A Pro series,https://www.tokopedia.com/blessingcombali/smar...,WAJIB Membaca CATATAN TOKO\nWAJIB Video Unboxi...,1729800,215,5.0,38,Monitor Tabung
3,11108003873,AQUA Elektronik AQR-D225(MDS) 1 pintu 180L,https://www.tokopedia.com/rossielektroni/aqua-...,AQUA Elektronik AQR-D225 1Door 180 L\n\nAQR-D2...,1933000,11,5.0,11,Kulkas
4,100413508806,GARANSI 1 TAHUN! BARDI ZigBee Smart Gateway,https://www.tokopedia.com/technobitzzz/garansi...,BARDI Zigbee Gateway adalah jembatan antara pe...,469000,2,NaN,398,Remote IO

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1143 entries, 0 to 1142
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    1143 non-null   int64
 1   product_name  1143 non-null   object
 2   url           1143 non-null   object
 3   description   1118 non-null   object
 4   price         1143 non-null   int64
 5   sold_count    1143 non-null   int64
 6   rating        949 non-null    float64
 7   total_stock   1143 non-null   int64
 8   category      1143 non-null   object
dtypes: float64(1), int64(4), object(4)
memory usage: 80.5+ KB

In [67]:
import re
import nltk
from collections import Counter
from nltk.corpus import stopwords

# --- download stopwords bahasa Indonesia (sekali aja perlu jalanin) ---
nltk.download("stopwords")

# --- ambil stopwords Indonesia ---
stopwords_id = set(stopwords.words("indonesian"))

# --- kolom yang akan dianalisis ---
cols_to_check = [
    "product_id", "product_name", "description", 
    "price", "sold_count", "rating", "total_stock", "category"
]

def get_most_common_words(series, n=10):
    text = " ".join(series.dropna().astype(str))
    words = re.findall(r'\w+', text.lower())
    
    filtered = []
    for w in words:
        # skip angka murni
        if w.isdigit():
            continue
        # skip stopwords
        if w in stopwords_id:
            continue
        filtered.append(w)
    
    return Counter(filtered).most_common(n)

# --- loop tiap kolom ---
for col in cols_to_check:
    print(f"\n=== Most Common Words in '{col}' ===")
    common_words = get_most_common_words(df[col], n=10)
    for word, count in common_words:
        print(f"{word}: {count}")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\vivin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

=== Most Common Words in 'product_id' ===

=== Most Common Words in 'product_name' ===
wanita: 201
pria: 174
tas: 128
sekolah: 123
anak: 121
bayi: 115
celana: 112
paket: 100
premium: 90
olahraga: 89

=== Most Common Words in 'description' ===
cm: 1344
produk: 1331
x: 1006
bahan: 925
ukuran: 830
warna: 613
barang: 612
kulit: 560
size: 553
cocok: 513

=== Most Common Words in 'price' ===

=== Most Common Words in 'sold_count' ===

=== Most Common Words in 'rating' ===

=== Most Common Words in 'total_stock' ===

=== Most Common Words in 'category' ===
pria: 122
wanita: 116
android: 72
os: 72
celana: 60
tas: 54
bayi: 47
ransel: 45
alat: 43
kaos: 39

In [68]:
# --- kumpulkan semua kata ---
all_words = []
for col in cols_to_check:
    common_words = get_most_common_words(df[col], n=None)  # ambil semua kata
    all_words.extend(common_words)

# --- gabungkan count dari semua kolom ---
total_counter = Counter()
for word, count in all_words:
    total_counter[word] += count

# --- ambil top 300 ---
top_words = total_counter.most_common(500)

# --- jadikan DataFrame ---
df_top_words1 = pd.DataFrame(top_words, columns=['word', 'count'])
df_top_words1.head

<bound method NDFrame.head of              word  count
0              cm   1347
1          produk   1336
2               x   1009
3           bahan    963
4          ukuran    842
..            ...    ...
495       standar     52
496  membersihkan     52
497            wi     52
498            si     52
499     frekuensi     52

[500 rows x 2 columns]>

In [69]:
## Most Common words dari kedua data

In [70]:
df_top_words_combined = pd.concat([df_top_words1, df_top_words2])
df_top_words_combined = df_top_words_combined.groupby('word', as_index=False)['count'].sum()
df_top_words_combined = df_top_words_combined.sort_values(by='count', ascending=False).reset_index(drop=True)

df_top_words_combined.head(30)

          word  count
0       produk   1367
1           cm   1347
2            x   1009
3        bahan    963
4       ukuran    842
5       barang    722
6        warna    657
7        kulit    589
8         anak    571
9         size    569
10      celana    554
11       cocok    530
12       paket    510
13  pengiriman    477
14      wanita    447
15        pria    445
16     lingkar    430
17      sesuai    423
18       mudah    420
19         tas    408
20     premium    400
21     garansi    392
22        bayi    390
23         air    365
24       video    362
25         isi    342
26    memiliki    331
27        baju    325
28    membantu    324
29      nyaman    320

In [71]:
import re
import pandas as pd

# slang Indonesia yang umum (bisa ditambah lagi)
SLANG_SEED = {
    # ketawa
    "wkwk","wk","wkwkwk","hahaha","hehe","huhu","hadeh",
    # kasar / makian
    "anjay","anjir","anjirr","anj","asu","goblok","tolol","coeg","cuk","tai","taii",
    # singkatan
    "cmiiw","btw","lol","gw","lu","loe","gmn","gk","ga","nggak","udh","udah","yg",
    "brb","afk","idk","irl","imo","imo","rip","fyi","otw",
    # sapaan
    "bro","sist","cuy","cuyy","ciy","gan","bosque","juragan",
    # gaya
    "mantul","mager","gabut","alay","santuy","keren","cihuy","asyik","asik","yoi","kuy"
}

SLANG_RULES = [
    # ketawa berulang
    ("repeated_laugh", re.compile(r"^(?:ha|he|hi|hu|wk|wkwk|x){2,}$")),

    # elongated huruf akhir (cuyyy, brooo, mantappp)
    ("elongated", re.compile(r"^[a-z]{2,}([a-z])\1{2,}$")),

    # slang angka → huruf (4l4y, g4nt3ng, 3aa)
    ("leet_slang", re.compile(r"^(?=.*[0-9])(?=.*[a-z])[a-z0-9]{3,}$")),

    # whitelist slang pendek (harus ada di SLANG_SEED)
    ("seeded", re.compile(r"^[a-z]{2,10}$")),
]
def detect_slangs(df_words: pd.DataFrame, min_count: int = 5) -> pd.DataFrame:
    rows = []
    for _, row in df_words.iterrows():
        w = str(row["word"]).lower()
        c = int(row["count"])
        
        if c < min_count:
            continue
        if not re.fullmatch(r"[a-z0-9]+", w):
            continue

        matched = None
        for name, rx in SLANG_RULES:
            if rx.match(w):
                # kalau rule "seeded", cek dulu harus ada di SLANG_SEED
                if name == "seeded" and w not in SLANG_SEED:
                    continue
                matched = name
                break

        if not matched:
            continue

        rows.append({"word": w, "count": c, "rule": matched})

    return (
        pd.DataFrame(rows)
        .sort_values(["count","word"], ascending=[False, True])
        .reset_index(drop=True)
    )
    
# contoh pakai:
df_slangs = detect_slangs(df_top_words_combined, min_count=5)
print(df_slangs.head(40))

     word  count        rule
0      yg    154      seeded
1     8gb    123  leet_slang
2   256gb     86  leet_slang
3    16gb     81  leet_slang
4   512gb     76  leet_slang
5     5cm     72  leet_slang
6   128gb     62  leet_slang
7     1tb     59  leet_slang
8      ga     19      seeded
9     gan     14      seeded
10   udah     11      seeded
11  nggak      8      seeded
12     gk      7      seeded